"""Empirical galaxy SED prior from DESI spectra and template fits."""

from typing import Any

from .desi_data import ensure_desi_healpix, get_local_desi_paths
from .fit_sed_prior_kde import (
    DEFAULT_GAUSSIANIZED_KDE_SAMPLES,
    GAUSSIANIZED_KDE_VERSION,
    coeffs_from_sample_row,
    fit_and_save_gaussianized_kde,
    fit_and_save_gaussianized_kde_for_run,
    fit_gaussianized_kde,
    fit_gaussianized_kde_from_artifact,
    load_gaussianized_kde,
    load_prior_training_table,
    load_sed_prior_kde,
    mode_central_params_from_artifact,
    sample_sed_prior,
    sample_sed_prior_kde,
    samples_to_coeffs,
    save_gaussianized_kde,
    save_sed_prior_kde,
)
from .paths import (
    DEFAULT_EMPIRICAL_PRIOR_DIR,
    DEFAULT_EMPIRICAL_PRIOR_VARIANT,
    DEFAULT_HEALPIX,
    EMPIRICAL_PRIOR_ROOT_DIR,
    NUM_VISITS_EXPERIMENT,
    SED_PRIOR_KDE_GAUSSIANIZED_FILENAME,
    SED_PRIOR_KDE_NATIVE_FILENAME,
    get_bedcosmo_scratch,
    get_desi_candidate_manifest_path,
    get_desi_data_dir,
    get_desi_training_data_dir,
    get_healpix_fit_dir,
    get_num_visits_scratch,
    get_prior_build_dir,
    get_prior_kde_gaussianized_path,
    get_prior_kde_path,
    get_prior_weights_csv,
    get_scratch_root,
    get_template_dir,
)
from .sed_prior import (
    EMPIRICAL_ARTIFACT_DIR,
    SED_PRIOR_KDE_FILENAMES,
    EmpiricalPriorPool,
    EmpiricalSedPrior,
    build_gpu_prior_pool,
    canonicalize_density_type,
    config_density_type,
    copy_sed_prior_artifacts,
    resolve_prior_dir,
    resolve_runtime_prior_root,
    sample_prior_batch,
    score_kde_artifact,
    sed_prior_flow_artifact_path,
    sed_prior_kde_artifact_path,
    snapshot_sed_prior,
)
from .simplex import (
    PARAMETERIZATION_CLR,
    PARAMETERIZATION_ILR,
    clr_to_weights,
    ilr_basis,
    ilr_to_weights,
    ilr_to_weights_torch,
    prior_clr_feature_names,
    prior_feature_names,
    prior_ilr_feature_names,
    split_feature_matrix,
    weights_to_clr,
    weights_to_ilr,
)
from .template_config import (
    empirical_prior_build_name,
    empirical_prior_variant,
    format_reduced_templates,
    materialize_empirical_prior_args,
    n_templates_for,
    parse_reduced_templates,
    resolve_template_param,
)
from .templates import (
    DEFAULT_TEMPLATE_DIR,
    DEFAULT_TEMPLATE_PARAM_6D,
    DEFAULT_TEMPLATE_PARAM_12D,
    load_eazy_template_bank,
    load_eazy_templates,
)


def build_prior(*args: Any, **kwargs: Any) -> Any:
    """Compatibility wrapper for :mod:`empirical.eazy.build_prior`."""
    from .eazy.build_prior import build_prior as _build_prior

    return _build_prior(*args, **kwargs)


def combine_healpix_weights(*args: Any, **kwargs: Any) -> Any:
    """Compatibility wrapper for :mod:`empirical.eazy.combine_healpix_weights`."""
    from .eazy.combine_healpix_weights import combine_healpix_weights as _combine

    return _combine(*args, **kwargs)

__all__ = [
    "DEFAULT_EMPIRICAL_PRIOR_DIR",
    "DEFAULT_EMPIRICAL_PRIOR_VARIANT",
    "DEFAULT_HEALPIX",
    "DEFAULT_TEMPLATE_PARAM_12D",
    "DEFAULT_TEMPLATE_PARAM_6D",
    "DEFAULT_TEMPLATE_DIR",
    "NUM_VISITS_EXPERIMENT",
    "PARAMETERIZATION_CLR",
    "PARAMETERIZATION_ILR",
    "DEFAULT_GAUSSIANIZED_KDE_SAMPLES",
    "GAUSSIANIZED_KDE_VERSION",
    "fit_and_save_gaussianized_kde",
    "fit_and_save_gaussianized_kde_for_run",
    "fit_gaussianized_kde",
    "fit_gaussianized_kde_from_artifact",
    "EMPIRICAL_ARTIFACT_DIR",
    "EMPIRICAL_PRIOR_ROOT_DIR",
    "SED_PRIOR_KDE_FILENAMES",
    "SED_PRIOR_KDE_GAUSSIANIZED_FILENAME",
    "SED_PRIOR_KDE_NATIVE_FILENAME",
    "canonicalize_density_type",
    "config_density_type",
    "clr_to_weights",
    "copy_sed_prior_artifacts",
    "resolve_prior_dir",
    "resolve_runtime_prior_root",
    "sed_prior_flow_artifact_path",
    "sed_prior_kde_artifact_path",
    "snapshot_sed_prior",
    "EmpiricalPriorPool",
    "EmpiricalSedPrior",
    "build_prior",
    "build_gpu_prior_pool",
    "combine_healpix_weights",
    "coeffs_from_sample_row",
    "ensure_desi_healpix",
    "get_bedcosmo_scratch",
    "get_desi_data_dir",
    "get_desi_candidate_manifest_path",
    "get_desi_training_data_dir",
    "get_template_dir",
    "get_healpix_fit_dir",
    "get_local_desi_paths",
    "get_num_visits_scratch",
    "get_prior_build_dir",
    "get_prior_kde_gaussianized_path",
    "get_prior_kde_path",
    "get_prior_weights_csv",
    "get_scratch_root",
    "load_eazy_template_bank",
    "load_eazy_templates",
    "empirical_prior_build_name",
    "empirical_prior_variant",
    "format_reduced_templates",
    "materialize_empirical_prior_args",
    "n_templates_for",
    "parse_reduced_templates",
    "resolve_template_param",
    "load_prior_training_table",
    "load_sed_prior_kde",
    "load_gaussianized_kde",
    "mode_central_params_from_artifact",
    "ilr_basis",
    "ilr_to_weights",
    "ilr_to_weights_torch",
    "prior_feature_names",
    "prior_clr_feature_names",
    "prior_ilr_feature_names",
    "weights_to_clr",
    "weights_to_ilr",
    "sample_prior_batch",
    "split_feature_matrix",
    "sample_sed_prior",
    "sample_sed_prior_kde",
    "samples_to_coeffs",
    "save_sed_prior_kde",
    "save_gaussianized_kde",
    "score_kde_artifact",
]
