# Training arguments for variable_redshift experiment
# Organized by cosmological model

base:
  cosmo_model: base
  mlflow_exp: base
  pyro_seed: 1
  nf_seed: 1
  priors_path: variable_redshift/priors.yaml
  flow_type: MAF
  transform_input: true
  activation: elu
  n_transforms: 5
  cond_hidden_size: 256
  cond_n_layers: 4
  mnn_hidden_size: 256
  mnn_n_layers: 4
  mnn_signal: 32
  nf_transform: affine
  spline_bins: 16
  fixed_design: false
  design_step: 0.1
  design_lower: 0.2
  design_upper: 2.5
  sigma_D_H: 0.2
  sigma_D_M: 0.2
  total_steps: 50000
  optimizer: Adam
  initial_lr: 0.0001
  final_lr: 0.0
  grad_clip: 0.0
  warmup_fraction: 0.05
  scheduler_type: cosine
  n_cycles: 1
  gamma: 0.1
  step_freq: 1
  checkpoint_step_freq: 1000
  n_particles_per_device: 201
  include_D_M: false
  verbose: true

base_omegak:
  cosmo_model: base_omegak
  mlflow_exp: base_omegak
  pyro_seed: 1
  nf_seed: 1
  priors_path: variable_redshift/priors.yaml
  flow_type: MAF
  transform_input: true
  activation: elu
  n_transforms: 6
  cond_hidden_size: 256
  cond_n_layers: 5
  mnn_hidden_size: 256
  mnn_n_layers: 5
  mnn_signal: 32
  nf_transform: affine
  spline_bins: 16
  fixed_design: false
  design_step: 0.1
  design_lower: 0.5
  design_upper: 5.0
  sigma_D_H: 0.2
  sigma_D_M: 0.2
  total_steps: 50000
  optimizer: Adam
  initial_lr: 0.0001
  final_lr: 0.0
  grad_clip: 0.0
  warmup_fraction: 0.05
  scheduler_type: cosine
  n_cycles: 1
  gamma: 0.1
  step_freq: 1
  checkpoint_step_freq: 1000
  n_particles_per_device: 201
  include_D_M: false
  verbose: true

base_w:
  cosmo_model: base_w
  mlflow_exp: base_w
  pyro_seed: 1
  nf_seed: 1
  priors_path: variable_redshift/priors.yaml
  flow_type: NAF
  transform_input: true
  activation: elu
  n_transforms: 6
  cond_hidden_size: 256
  cond_n_layers: 5
  mnn_hidden_size: 256
  mnn_n_layers: 5
  mnn_signal: 32
  nf_transform: affine
  spline_bins: 16
  fixed_design: false
  design_step: 0.1
  design_lower: 0.5
  design_upper: 5.0
  sigma_D_H: 0.2
  sigma_D_M: 0.2
  total_steps: 60000
  optimizer: Adam
  initial_lr: 0.0001
  final_lr: 0.0
  grad_clip: 0.0
  warmup_fraction: 0.05
  scheduler_type: cosine
  n_cycles: 1
  gamma: 0.1
  step_freq: 1
  checkpoint_step_freq: 1000
  n_particles_per_device: 101
  include_D_M: false
  verbose: true

base_w_wa:
  cosmo_model: base_w_wa
  mlflow_exp: variable_redshift_base_w_wa
  pyro_seed: 1
  nf_seed: 1
  priors_path: variable_redshift/priors.yaml
  flow_type: NAF
  transform_input: true
  activation: elu
  n_transforms: 8
  cond_hidden_size: 256
  cond_n_layers: 6
  mnn_hidden_size: 256
  mnn_n_layers: 6
  mnn_signal: 32
  nf_transform: affine
  spline_bins: 16
  fixed_design: false
  design_step: 0.1
  design_lower: 0.5
  design_upper: 5.0
  sigma_D_H: 0.2
  sigma_D_M: 0.2
  total_steps: 80000
  optimizer: Adam
  initial_lr: 0.00008
  final_lr: 0.0
  grad_clip: 0.0
  warmup_fraction: 0.05
  scheduler_type: cosine
  n_cycles: 1
  gamma: 0.1
  step_freq: 1
  checkpoint_step_freq: 1000
  n_particles_per_device: 101
  include_D_M: false
  verbose: true

base_omegak_w_wa:
  cosmo_model: base_omegak_w_wa
  mlflow_exp: base_omegak_w_wa
  pyro_seed: 1
  nf_seed: 1
  priors_path: variable_redshift/priors.yaml
  flow_type: NAF
  transform_input: true
  activation: elu
  n_transforms: 10
  cond_hidden_size: 256
  cond_n_layers: 8
  mnn_hidden_size: 256
  mnn_n_layers: 8
  mnn_signal: 32
  nf_transform: affine
  spline_bins: 16
  fixed_design: false
  design_step: 0.1
  design_lower: 0.5
  design_upper: 5.0
  sigma_D_H: 0.2
  sigma_D_M: 0.2
  total_steps: 100000
  optimizer: Adam
  initial_lr: 0.00008
  final_lr: 0.0
  grad_clip: 0.0
  warmup_fraction: 0.08
  scheduler_type: cosine
  n_cycles: 1
  gamma: 0.1
  step_freq: 1
  checkpoint_step_freq: 1000
  n_particles_per_device: 101
  include_D_M: false
  verbose: true

